name: 'Check log with reviewdog'
description: 'Find log method of golang functions with reviewdog'
author: 'seipan'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
  workdir:
    description: 'working directory relative to the root directory'
    required: false
    default: ./

runs:
  using: 'composite'
  steps:
    - run: go get github.com/seipan/logfind/cmd/logfind
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
    - run: ${{ github.action_path }}/reviewdog.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
      shell: bash
